# Generated by Django 4.2.1 on 2023-06-08 07:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_image_path, verbose_name='プロフィール画像'),
        ),
    ]
