# Generated by Django 4.2.1 on 2023-06-09 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='deleted_at',
        ),
    ]
