# Generated by Django 4.2.1 on 2023-06-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_follow_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='view_timeline',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='タイムライン表示設定'),
        ),
    ]
