# Generated by Django 4.2.2 on 2023-06-12 13:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=image.models.upload_to_uuid)),
                ('trim_image', models.ImageField(blank=True, upload_to='images/user')),
                ('is_edited', models.BooleanField(blank=True, default=False)),
                ('position_x', models.IntegerField(blank=True, default=0)),
                ('position_y', models.IntegerField(blank=True, default=0)),
                ('zoom', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('upload_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trim_image', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_image',
            },
        ),
    ]
